export const SHUFFLE_DECK = 'SHUFFLE_DECK';
export const DEAL_CARDS = 'DEAL_CARDS';
export const BEGIN_TURN = 'BEGIN_TURN';
export const END_TURN = 'END_TURN';

export const CHANGE_BRICKS = 'CHANGE_BRICKS';
export const CHANGE_GEMS = 'CHANGE_GEMS';
export const CHANGE_RECRUITS = 'CHANGE_RECRUITS';

export const CHANGE_BRICK_PRODUCTION = 'CHANGE_BRICK_PRODUCTION';
export const CHANGE_GEM_PRODUCTION = 'CHANGE_GEM_PRODUCTION';
export const CHANGE_RECRUIT_PRODUCTION = 'CHANGE_RECRUIT_PRODUCTION';

export const CHANGE_BRICK_PRODUCTION_IF_LESS = 'CHANGE_BRICK_PRODUCTION_IF_LESS';
export const CHANGE_RECRUIT_PRODUCTION_IF_LESS = 'CHANGE_RECRUIT_PRODUCTION_IF_LESS';
export const CHANGE_TOWER_IF_LESS = 'CHANGE_TOWER_IF_LESS';
export const COPY_BRICK_PRODUCTION_IF_LESS = 'COPY_BRICK_PRODUCTION_IF_LESS';
export const CHANGE_WALL_IF_NO_WALL = 'CHANGE_WALL_IF_NO_WALL';

export const CHANGE_TOWER = 'CHANGE_TOWER';
export const CHANGE_WALL = 'CHANGE_WALL';
export const SWITCH_WALL = 'SWITCH_WALL';

export const RECEIVE_DAMAGE = 'RECEIVE_DAMAGE';
export const FLOOD_WATER = 'FLOOD_WATER';
export const LIGHTNING_SHARD = 'LIGHTNING_SHARD';

export const DISCARD_CARD = 'DISCARD_CARD';
export const DRAW_CARD = 'DRAW_CARD';
export const EQUALIZE_GEM_PRODUCTION = 'EQUALIZE_GEM_PRODUCTION';
